# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(null=True)),
                ('bottom_rack_slot', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetFieldValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_tracking.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AssetTypeContainmentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_tracking.AssetType')),
                ('can_contain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container', to='asset_tracking.AssetType')),
            ],
        ),
        migrations.CreateModel(
            name='AssetTypeField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_tracking.AssetType')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CommentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_tracking.Manufacturer')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_tracking.CommentType'),
        ),
        migrations.AddField(
            model_name='assetfieldvalue',
            name='asset_type_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_tracking.AssetTypeField'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_tracking.AssetType'),
        ),
        migrations.AddField(
            model_name='asset',
            name='contained_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asset_tracking.Asset'),
        ),
        migrations.AddField(
            model_name='asset',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_tracking.Model'),
        ),
    ]
